name: Sync Upstream CZSC

on:
  schedule:
    - cron: '0 2 * * 1'  # 每周一凌晨2点
  workflow_dispatch:     # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
      - name: Add upstream
        run: |
          git remote add upstream https://github.com/waditu/czsc.git || true
          git fetch upstream
          
      - name: Sync master
        run: |
          git checkout master
          git merge upstream/master --no-edit
          git push origin master
          
      - name: Sync development branch
        run: |
          git checkout vnpy-integration || git checkout -b vnpy-integration
          git merge master --no-edit
          git push origin vnpy-integration
